// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_tZ9WUFunGgHJfCRnx2DcNblVfYbmr08',
    appId: '1:229619088195:android:00824bf2753b91bf354df6',
    messagingSenderId: '229619088195',
    projectId: 'flutter-projects-ef9a9',
    databaseURL: 'https://flutter-projects-ef9a9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-projects-ef9a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8SW23r2s-b4H7h3q9LGYJkNqpxpDFIsY',
    appId: '1:229619088195:ios:4d9fddaaff19b393354df6',
    messagingSenderId: '229619088195',
    projectId: 'flutter-projects-ef9a9',
    databaseURL: 'https://flutter-projects-ef9a9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-projects-ef9a9.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );
}
